### ISSUE TITLE
Update please doc for drone 

### ISSUE THREAD

**Issue by UstyuzhaninAV** [fdeschenes/drone-grafana-annotation#2]
Update please doc for drone 
http://plugins.drone.io/fdeschenes/drone-grafana-annotation/

**Comment by felix-hellman** [comment]
Working example of drone docs if anyone has the same issue.

```yaml
- name: annotate-deploy
  image: fdeschenes/drone-grafana-annotation
  settings:
    api_key:
      from_secret: GRAFANA_API_KEY
    tags:
      - deploy
      - production
    text: "Deployed"
    url: https://grafana.example.com
  when:
    target:
      - production
    event:
     - promote
```
